# Generated by Django 3.0.8 on 2020-07-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
